# Generated by Django 4.2.2 on 2023-06-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_person_id_person_person_id_post_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='person_id',
            new_name='person',
        ),
    ]
