# Generated by Django 4.2.2 on 2023-06-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_person_id_post_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
