# Generated by Django 4.2.2 on 2023-06-30 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_person_age_alter_person_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
