# Generated by Django 4.2.2 on 2023-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=30)),
                ('rooms_number', models.IntegerField()),
                ('hotel_name', models.CharField(default='mans', max_length=50)),
            ],
        ),
    ]
