# Generated by Django 4.2.3 on 2023-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
    ]
